#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'apache2'
cookbook 'build-essential'
cookbook 'mysql'
cookbook 'php'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

cookbook 'MailCatcher',
  :git => 'https://github.com/bryantebeek/chef-mailcatcher',
  :ref => 'v0.1.3'
